### ISSUE TITLE
optical flow images are not allowed!

### ISSUE THREAD

**Issue by jihwan722** [yaorong0921/Driver-Intention-Prediction#11]
Hello @yaorong0921, The link containing the optical flow image has expired. Please update the link. I would greatly appreciate it！

After opening the link, the website displays:
- Der Link ist leider abgelaufen.
- Für den Link wurde festgelegt, dass er nach einem bestimmten Zeitraum abläuft. Wenden Sie sich an die Person, die diesen Link mit Ihnen geteilt hat.

**Comment by yaorong0921** [comment]
Dear @jihwan722 ,

Thank you for letting me know. Please try it again. It should work. 
Best wishes,

**Comment by jihwan722** [comment]
![error](https://github.com/yaorong0921/Driver-Intention-Prediction/assets/127845632/1d9c9021-95bb-4455-88f1-18973840b217)
Thank you for your reply! but The file "flownet_road_camera.zip" cannot be extracted.

**Comment by jihwan722** [comment]
Thank you for your reply!
