### ISSUE TITLE
ask for advise

### ISSUE THREAD

**Issue by Harlan728** [yaorong0921/Driver-Intention-Prediction#2]
Hi,
I wish to consult you on two questions.
1. the path gained when run the "n_fold_Brain4cars.py" were separated by '\',but not like the path  in given fold.csv separated by '/'.the paths are little confused .As following images.
![error](https://user-images.githubusercontent.com/82154701/114029426-10e25f80-98ac-11eb-84a4-5656cac3ddfa.PNG)
![1](https://user-images.githubusercontent.com/82154701/114029439-1475e680-98ac-11eb-9002-44fc7ab3b238.PNG)

2. I revised some of paths by my hands,and tried to run the "run-3DResnet" with part of face_camera dataset,the result are shown in the image below,and the data did not seem to be read in.
![1(1)](https://user-images.githubusercontent.com/82154701/114029625-471fdf00-98ac-11eb-82f3-86812d1197fa.PNG)

Best,

**Comment by yaorong0921** [comment]
Hi, 
1. I think the reason for the backslash is that you are probably running the "n_fold_Brain4cars.py" using the windows system. Pls replace all the "\\" in the generated.csv files and see whether it works.
2.  Pls simply give the whole file path to data_file_path (line 62 in Brain4cars.py). Again, the "os.path.join" may give you the '\\'

**Comment by Harlan728** [comment]
Hi,

I would like to learn whether the following understandings of this paper are correct?

1. According to this paper, I need to build a classifier(decoder&FC) to evaluate  ConvLSTM

2. The classifier will be trained by both features or only by the features extracted from outside videos

3. Since the decoder has been defined in "convolution_lstm.py", it means that I only need to build a full connection layer

**Comment by Harlan728** [comment]
Another question
In order to train the ConvLSTM,do I just need to run “run-ConvLSTM.sh” ?
And to evaluate it the trained model, do I need to add two args in the “run-ConvLSTM.sh”?
--resume_path /path_to_model/0_fifth.pth
--no_train

**Comment by yaorong0921** [comment]
Hi, 
1. to evaluate ConvLSTM, you do not have to build the classifier, since this module will give you the predicted optical flow images. So you evaluate with metrics in Table IV.
2. The classifier will be trained with features from both sides.
3. Yes, the classifier is not included in convolution_lstm, since it used features from both sides as input. And you need to build the fc layers by yourself after you combining the features (Table II bottom part).
4. Yes. But pls be aware that the 0_fifth.pth is trained on my split 0_fold.
I hope it helps you!

Best,

**Comment by Harlan728** [comment]
Hi，

I am very grateful to you for your advice！
There are still two problems:
1. I cannot find 3D-ResNet in the folder of models, and "pre_act_resnet.py" and 'wide_resnet.py' were not mentioned in the paper
![image](https://user-images.githubusercontent.com/82154701/115838622-7574f100-a44c-11eb-8d6f-4b43142d1c20.png)

2. It is difficult to resolve this error when train ConvLSTM with optical flow images
![1](https://user-images.githubusercontent.com/82154701/115840756-9a6a6380-a44e-11eb-8982-8cfbf8c5c437.PNG)

Best,

**Comment by yaorong0921** [comment]
Hi,
1. 3D-ResNet is "resnet.py".  "pre_act_resnet.py" and 'wide_resnet.py'  were not used in paper. But they wont influence training with resnet, if you do not use them.
2. It seems that there is no data loaded.  Pls make sure the optical flow images are loaded. If the dataloader works with inside images, it should also work for outside images. The printed-out path could be from line 51 in Brain4cars.py. Please check it.

Best,
