### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by JunsFu** [yaorong0921/Driver-Intention-Prediction#9]
Hello, the links to the pre-trained models you provided are invalid. Could you please re-upload them? Thank you very much!

**Comment by yaorong0921** [comment]
Hi @JunsFu0222 ,
thanks for letting me know. Could you please try it agian?

**Comment by JunsFu** [comment]
Thank you for your help. I have already downloaded it!




傅俊松
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yaorong0921/Driver-Intention-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月6日(星期五) 晚上11:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yaorong0921/Driver-Intention-Prediction] Link is broken (Issue #9)





 
Hi @JunsFu0222 ,
 thanks for letting me know. Could you please try it agian?
